### ISSUE TITLE
i18n - params / 투표 이벤트 관련

### ISSUE THREAD

**Issue by jsc7727** [Cocktail-Masters/Banana-Vote-FE#106]
고민을 해봅시다

- [x] i18n의 params는 어떻게 가져올지
- [x] 투표 이벤트 관련 컴포넌트는 어떤 부분을 재사용 할지

**Comment by jsc7727** [comment]
serverside 코드 쪽 컴포넌트에서 받는 인자값에 params가 있는지 확인해야함

**Comment by jsc7727** [comment]
serverside에서 params로 받아서 각 컴포넌트에 props로넘겨주면 됩니다.
![image](https://user-images.githubusercontent.com/20225380/230327611-8f369569-ef7c-457f-8b05-acad0f64c9f0.png)

**Comment by TypingOK** [comment]
클라이언트 사이드에서도 params 받아올 수 있는지 테스트 요망

**Comment by jsc7727** [comment]
> 클라이언트 쪽에서도 params를 받아올 수 있는지 테스트 요망

![image](https://user-images.githubusercontent.com/20225380/230328655-5b368cdd-32a1-4db5-a384-32b86bebba32.png)
****

국제화 사용할 수 있네요 : )
